### ISSUE TITLE
how to enable grep for the fixme engine to ignore a pattern

### ISSUE THREAD

**Issue by zramsay** [codeclimate/codeclimate-grep#10]
- see https://codeclimate.com/github/ipfs/go-ipfs/pull/3949
- i need the fixme engine to use the grep engine to ignore `context.TODO()`

**Comment by pointlessone** [comment]
As far as I can tell, there's no way to set up dependencies between engines. You may want to limit fixme engine to catch mentions that do not require any context and use grep engine for contextual `TODO`.

**Comment by pointlessone** [comment]
@zramsay I will close this issue now. Feel free to reopen if you have anything to add to move this forward.
