### ISSUE TITLE
Checking for hard tabs

### ISSUE THREAD

**Issue by joshminnie** [codeclimate/codeclimate-grep#11]
I'm trying to use the grep engine for checking for hard tabs in our codebase, but it's returning a significant amount of false positives. I've use `\t` literal to check. Is there another form of this that I might use?

**Comment by toddmazierski** [comment]
Hi, @joshminnie! Thanks for the report. I think I'm able to reproduce this bug. I'm not aware of any alternates to the tab literal `\t` at the moment. Please stand by!

**Comment by toddmazierski** [comment]
Hi @joshminnie,

It looks as though the tab literal needs to be wrapped in double quotes. Mind trying this and let me know if you have any success?

```yaml
pattern: "\t"
```

**Comment by joshminnie** [comment]
That was the fix. Follow up question: do all regex patterns need to be wrapped in quotes?

**Comment by toddmazierski** [comment]
Great!

> do all regex patterns need to be wrapped in quotes?

No, the examples in the [README](https://github.com/codeclimate/codeclimate-grep/blob/master/README.md), for example, aren't quoted. It appears to be a quirk of YAML parsing that it's required in this case.
