### ISSUE TITLE
Checking for blank line at EOF

### ISSUE THREAD

**Issue by joshminnie** [codeclimate/codeclimate-grep#12]
Is it possible with the grep engine to ensure that the file ends in a blank line?

**Comment by pointlessone** [comment]
I don't think it's possible. This engine uses GNU grep which is strictly line-based and lacks any anchors for EOF. You may try googling for a GNU grep regexp that does that but quick look didn't turn up anything useful for me.

---

I'll close this issue now. Feel free to reopen if you believe this is a bug of this engine and you have it working with grep in terminal. Also please do share a regexp if you happen to find one. Thank you.

**Comment by maxjacobson** [comment]
Thanks for sharing your idea, btw. This sounds like something that could be its own micro engine.
